name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3  # Checkout code

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        flake8 src/ tests/

  train:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3  # Checkout code

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install mlflow

    - name: Train model
      run: |
        python src/model.py  # Train and save the model artifacts

    - name: Save model artifact
      uses: actions/upload-artifact@v3
      with:
        name: model-artifacts
        path: |
          src/model.h5
          src/tokenizer.pkl

  test:
    needs: train
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3  # Checkout code

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install .

    - name: Set PYTHONPATH environment variable
      run: |
        echo "PYTHONPATH=$(pwd)/src" >> $GITHUB_ENV
        echo "PYTHONPATH is set to $PYTHONPATH"

    - name: Run tests
      run: |
        pytest tests/ --disable-warnings

  deploy:
    needs: test
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v3  # Checkout code
  
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
  
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install mlflow gunicorn

    - name: Download model artifact
      uses: actions/download-artifact@v3
      with:
        name: model-artifacts  # Retrieve the model artifacts from the train job
  
    - name: Run Flask application with Gunicorn
      run: |
        gunicorn -w 4 -b 0.0.0.0:8000 app:app &  # Start the Flask app in the background
        sleep 10  # Allow time for the app to start
  
    - name: Integration Test
      run: |
        curl -f http://127.0.0.1:8000 || exit 1  # Test the root endpoint
  
    - name: Stop Flask Application
      run: pkill gunicorn  # Gracefully stop Gunicorn

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3  # Checkout code

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8

    - name: Run linter
      run: |
        flake8 src tests --count --select=E9,E7,E5,F,C901,W --show-source --statistics

